### ISSUE TITLE
update manager: software sources doesnt come up

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#13]
![screenshot_20180224_141116](https://user-images.githubusercontent.com/840070/36630801-a2d96f2c-196c-11e8-9b9d-5ab568400b45.png)

**Comment by llelectronics** [comment]
Probably missing software-properties-kde. Can you check if it comes up with this package installed.

**Comment by llelectronics** [comment]
So even after kdesudo is in place it won't start because python-apt template for codename buster is missing still in upstream python-apt. 
This makes also add-apt-repository and other scripts fail. 

I fixed it now by updating base-files for Netrunner Core to not use the codename **buster** in **lsb-release** but rather testing. 
See this commit: https://github.com/netrunner-core/base-files/commit/719b5256e9a564de4232111afcd9e67e7b769f40
