### ISSUE TITLE
desktop: obvious: bookmarks toolbar ONLY has "getting started" after installation

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#39]
![screenshot_20180309_133307](https://user-images.githubusercontent.com/840070/37207718-82f5fc5c-239e-11e8-983d-c93c39ada0bf.png)

**Comment by llelectronics** [comment]
Should be fixed with: https://github.com/netrunner-desktop/calamares-desktop/commit/31adcd573e17d5701daa7c6b8d2c38fca3661761 
But testing right now what happens if you don't have internet connection during install and the localization package can't be downloaded. Might needs fix changes for cck2 again to handle that case aswell.

**Comment by llelectronics** [comment]
Tested the last case no internet connection during install which leads to no localized firefox. Though "Getting started" got removed from bookmarks. So should be fixed on next iso.
